#!/bin/sh

echo "Content-type: application/json"
echo ""

# authenticate
qaul_auth=`/qaul/bin/authenticate.sh`

if [ "$qaul_auth" = "1" ]
then
	# configure eth interface
	/qaul/bin/eth_lan.sh

	echo "{\"s\":1}"
else
	echo "{\"s\":0}"
fi
