#!/bin/sh

echo "Content-type: application/json"
echo ""

# authenticate
qaul_auth=`/qaul/bin/authenticate.sh`

if [ "$qaul_auth" = "1" ]
then
	# switch internet on
	/qaul/bin/internet_off.sh

	echo "{\"s\":1}"
else
	echo "{\"s\":0}"
fi
