#!/bin/sh

echo "Content-type: application/json"
echo ""

# authenticate
qaul_auth=`/qaul/bin/authenticate.sh`

if [ "$qaul_auth" = "1" ]
then
	# receive POST variables
	if [ "$REQUEST_METHOD" = POST ]; then
		read -n $CONTENT_LENGTH QUERY_STRING_POST
			
		IFS="&="
		set -- $QUERY_STRING_POST
		
		NEWPASSWORD=`echo "$2" | sed -E "s/^([^ ;\|\/\$\"]*)|(.*)$/\1/"`
		
		if [ "$NEWPASSWORD" != "" ]
		then
			# set new password
			/qaul/bin/newpassword.sh "$NEWPASSWORD"
		
			echo "{\"s\":1}"
		else
			echo "{\"s\":0}"
		fi
	else
		echo "{\"s\":0}"
	fi
else
	echo "{\"s\":0}"
fi
