#!/bin/sh

echo "Content-type: application/json"
echo ""

# authenticate
qaul_auth=`/qaul/bin/authenticate.sh`

if [ "$qaul_auth" = "1" ]
then
	# receive POST variables
	if [ "$REQUEST_METHOD" = POST ]; then
		read -n $CONTENT_LENGTH QUERY_STRING_POST
	fi
	
	IFS="&="
	set -- $QUERY_STRING_POST

	# set new password
	/qaul/bin/newpassword.sh "$2"

	echo "{\"s\":1}"
else
	echo "{\"s\":0}"
fi
