/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qaul_qaul_NativeQaul */

#ifndef _Included_net_qaul_qaul_NativeQaul
#define _Included_net_qaul_qaul_NativeQaul
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    libInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_libInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    libExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_libExit
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    webserverStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qaul_qaul_NativeQaul_webserverStart
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    configStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_configStart
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    captiveStart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qaul_qaul_NativeQaul_captiveStart
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    ipcConnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qaul_qaul_NativeQaul_ipcConnect
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    ipcClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qaul_qaul_NativeQaul_ipcClose
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    ipcSendCom
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_ipcSendCom
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    getIP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_qaul_qaul_NativeQaul_getIP
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    existsUsername
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qaul_qaul_NativeQaul_existsUsername
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    configurationFinished
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_configurationFinished
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    filePicked
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_filePicked
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    getAppEventOpenPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_qaul_qaul_NativeQaul_getAppEventOpenPath
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    timedCheckAppEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_qaul_qaul_NativeQaul_timedCheckAppEvent
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    timedSocketReceive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_timedSocketReceive
  (JNIEnv *, jobject);

/*
 * Class:     net_qaul_qaul_NativeQaul
 * Method:    timedDownload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qaul_qaul_NativeQaul_timedDownload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
