#!/bin/sh

## json configuration file

# send configuration
echo "Content-type: text/json"
echo ""
echo "{\n"

# check authentication
qaul_auth=`/qaul/bin/authenticate.sh`

# send info
if ["$qaul_auth" = "1"]
then
	echo "\"auth\":$qaul_auth,\n"

	echo '"internet":'
	qaul_internet=`uci show olsrd.dyn_gw.ignore`
	if ["$qaul_internet" = "0"]
	then
		echo "1,\n"
	else
		echo "0,\n"
	fi

	qaul_storage=`cat /qaul/config/storage`
	echo "\"storage\":$qaul_storage,\n"

	qaul_mobile=`cat /qaul/config/mobile`
	echo "\"mobile\":$qaul_mobile,\n"

	qaul_eth_config=`cat /qaul/config/eth_config`
	echo "\"eth_config\":\"$qaul_eth_config\"\n"

	qaul_eth=`cat /qaul/config/eth`
	echo "\"eth\":\"$qaul_eth\"\n"
else
	echo "\"auth\":$qaul_auth\n"
fi

echo "}"
