#!/bin/sh

## json configuration file

# send configuration
echo "Content-type: application/json"
echo ""
echo "{"

# check authentication
qaul_auth=`/qaul/bin/authenticate.sh`

# send info
if [ "$qaul_auth" = "1" ]
then
	qaul_pw_default=`cat /etc/shadow | grep "root:$1$IxLAgyK8$k9p3I2IDnER48L8H49lPq/:"`
	
	if [ "$qaul_pw_default" = "" ]
	then
		echo "\"auth\":$qaul_auth,"

		echo '"internet":'
		qaul_internet=`uci show olsrd.dyn_gw.ignore`
		if [ "$qaul_internet" = "0" ]
		then
			echo "1,"
		else
			echo "0,"
		fi

		qaul_storage=`cat /qaul/config/storage`
		echo "\"storage\":$qaul_storage,"

		qaul_mobile=`cat /qaul/config/mobile`
		echo "\"mobile\":$qaul_mobile,"

		qaul_eth_config=`cat /qaul/config/eth_config`
		echo "\"eth_config\":\"$qaul_eth_config\","

		qaul_eth=`cat /qaul/config/eth`
		echo "\"eth\":\"$qaul_eth\","
		
		# display ip's
		echo "\"config\":["
		comma=""
		value=`uci get network.qaulwifi.ipaddr 2>&1`
		if [ "$value" != "uci: Entry not found" ]; then
			echo "\"WLAN: $value\""
			comma=","
		fi
		value=`uci get network.wan.ipaddr 2>&1`
		if [ "$value" != "uci: Entry not found" ]; then
			echo "$comma\"WAN: $value\""
			comma=","
		fi
		value=`uci get network.qauleth.ipaddr 2>&1`
		if [ "$value" != "uci: Entry not found" ]; then
			echo "$comma\"ETH qaul: $value\""
			comma=","
		fi
		value=`uci get network.lan.ipaddr 2>&1`
		if [ "$value" != "uci: Entry not found" ]; then
			echo "$comma\"LAN: $value\""
			comma=","
		fi
		echo "]"
	else
		echo "\"auth\":2"
	fi
else
	echo "\"auth\":0"
fi

echo "}"
