#!/bin/sh

echo "Content-type: text/json"
echo ""

# authenticate

# receive POST variables
if [ "$REQUEST_METHOD" = POST ]; then
	read -n $CONTENT_LENGTH QUERY_STRING_POST
fi
IFS="&="
set -- $QUERY_STRING_POST

# configure mobile internet
/qaul/bin/mobile_config.sh "$2" "$4" "$6" "$8"

echo "{\"s\":1}"
