#!/bin/sh

echo "Content-type: text/json"
echo ""

# authenticate

# receive POST variables
if [ "$REQUEST_METHOD" = POST ]; then
	read -n $CONTENT_LENGTH QUERY_STRING_POST
fi
IFS="&="
set -- $QUERY_STRING_POST

# set new password
/qaul/bin/newpassword.sh "$2"

echo "{\"s\":1}"
